CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(32),
    published_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    author VARCHAR(255) NOT NULL,
    text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_comments_book FOREIGN KEY (book_id)
        REFERENCES books(id) ON DELETE CASCADE
);

DELETE FROM comments;
DELETE FROM books;

INSERT INTO books (id, title, author, isbn, published_at) VALUES
    (1, 'Effective Java', 'Joshua Bloch', '978-0134685991', CURRENT_TIMESTAMP),
    (2, 'Clean Code', 'Robert C. Martin', '978-0132350884', CURRENT_TIMESTAMP),
    (3, 'Java Concurrency in Practice', 'Brian Goetz', '978-0321349606', CURRENT_TIMESTAMP);